
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">HMDoll</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Главная<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Приобретение и доставка</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">О нас...</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
			<label for="inputLanguage" class=" text-light">Язык/Language:<span>&nbsp &nbsp;&nbsp;</span> </label>
			<select class="custom-select mr-sm-2" id="inputLanguage">
				<option value="1" selected >Русский</option>
				<option value="2">English</option>
			</select>		 
        </form>
      </div>
    </nav>

    <main role="main" class="container">

      <div class="jumbotron">
			<div class="row">
				<div class="col-sm-2">
				   <img src="img/hmd.gif" class="img-fluid" id="gal"  alt="logotype"> 
				</div>
				<div class="col-sm-10">
					<p class="h1 text-center">Куклы ручной работы</p>
					&nbsp;&nbsp;&nbsp;&nbsp;Здесь Вы можете найти замечательную куклу изготовленную для Вас. Все куклы производятся по оригинальным лекалам вручную. Мы вкладываем в каждую частичку своей души. Может какая-нибудь согреет Вас?
				</div>
			</div>
		
      </div>

	  <div class="container">
	  
		  <div class="album py-5 bg-light">
			<div class="container">

			  <div class="row">
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/IMG_20181018_131449.jpg" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px max-height: 100px">
					<img class="card-img-top" src="img/IMG_20180417_131423к.jpg" alt="Куколка">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/IMG_20181018_131449.jpg" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>

				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/IMG-20180415-WA0021.jpg" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/IMG-20180415-WA0006.jpg" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/iDF3DTq.jpeg" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>

				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/DSC08500.JPG" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/DSC08358.JPG" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
				<div class="col-md-4">
				  <div class="card mb-4 shadow-sm img-thumbnail max-width: 100px">
					<img class="card-img-top" src="img/DSC08396.jpg" alt="Sheep">
					<div class="card-body">
					  <p class="card-text">Текст, описывающий и характеризующий данный образец так, чтобы захотелось его купить</p>
					  <div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
						  <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
						  <button type="button" class="btn btn-sm btn-outline-secondary">Заказать</button>
						</div>
						<small class="text-muted">2500 руб.</small>
					  </div>
					</div>
				  </div>
				</div>
			  </div>
			</div>
		  </div>

	  </div>
    </main>
